version: "3"

volumes:
  webserver_nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Users/sboyd/Docker/docker-compose-lamp/www"
  # mysql_nfsmount:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
  #     device: ":/Users/sboyd/Docker/docker-compose-lamp/data/mysql"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.3.x-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - "webserver_nfsmount:/var/www/html"
      #- ${DOCUMENT_ROOT-./www}:/var/www/html
      #- ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      #- ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build:
      context: "./bin/mysql"
    container_name: '5.7-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    #volumes: 
      #- "mysql_nfsmount:/var/lib/mysql"
      #- ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      #- ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: docker
      PMA_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - '8080:80'
    # volumes: 
    #   - /sessions
  # redis:
  #   container_name: 'sc-redis'
  #   image: redis:latest
  #   ports:
  #     - "${HOST_MACHINE_REDIS_PORT}:6379"
